a71-common: Drop android.hardware.power.stats
* Fixes:
ERROR: files are incompatible: android.hardware.power.stats@1.0::IPowerStats/default is deprecated in compatibility matrix at FCM Version 6; it should not be served.
    because it matches android.hardware.power.stats@1.0::IPowerStats/default from /system/etc/vintf/compatibility_matrix.5.xml

Change-Id: Ib4f60b885a3ff6dd3e61538fdd418611a606a8f3